msrv = "1.82.0"
cognitive-complexity-threshold = 30
doc-valid-idents = ["CLI", "TOML", "API", "GitHub", "UUID"]
enum-variant-size-threshold = 256
large-error-threshold = 256
too-many-arguments-threshold = 6
type-complexity-threshold = 250