[package]
description = "Library for handling template logic for cargo-quickstart"
edition = "2021"
license = "MIT OR Apache-2.0"
name = "quickstart-lib"
rust-version = "1.82.0"
version = "0.0.2"

[dependencies]
camino = { workspace = true, features = ["serde"] }
cargo_metadata = { workspace = true, features = ["builder"] }
chrono = { workspace = true }
color-eyre = { workspace = true }
fs_extra = { workspace = true }
handlebars = { workspace = true }
ignore = { workspace = true }
pathdiff = { workspace = true }
serde = { workspace = true, features = ["derive"] }
thiserror = { workspace = true }
toml = { workspace = true }
which = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true, features = ["color"] }
camino = { workspace = true, features = ["proptest"] }
mockall = { workspace = true }
pretty_assertions = { workspace = true }
tempfile = { workspace = true }
which = { workspace = true, features = ["tracing"] }

[package.metadata.cargo-udeps.ignore]
dependencies = ["camino", "cargo_metadata", "fs_extra", "ignore", "toml"]
