[package]
name        = "quickstart-lib"
version     = "0.1.0"
edition     = "2021"
description = "Library for handling template logic for cargo-quickstart"
license     = "MIT OR Apache-2.0"

[dependencies]
serde          = { workspace = true, features = ["derive"] }
toml           = { workspace = true }
handlebars     = { workspace = true }
ignore         = { workspace = true }
fs_extra       = { workspace = true }
camino         = { workspace = true }
cargo_metadata = { workspace = true }
indicatif      = { workspace = true }
which          = { workspace = true }
