name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"
  # Disable sccache in CI environment
  RUSTC_WRAPPER: ""

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt, llvm-tools

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          # Add key based on Cargo.lock to ensure cache invalidation
          key: ${{ hashFiles('**/Cargo.lock') }}

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Install CI tools
        run: just ensure-ci-tools

      - name: Run CI checks
        run: just ci

      - name: Generate coverage report
        run: just cover

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./lcov.info
          fail_ci_if_error: false

  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Install cargo-msrv
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-msrv

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: msrv-${{ hashFiles('**/Cargo.lock') }}

      - name: Check MSRV
        run: just check-msrv

  docs:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
          key: docs-${{ hashFiles('**/Cargo.lock') }}

      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Build documentation
        run: just docs