name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: ""
  # Disable sccache in CI environment
  RUSTC_WRAPPER: ""

jobs:
  checks:
    name: Build, Clippy, Test, Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust (stable)
        uses: crusty-pie/toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools, clippy, rustfmt
          override: true

      - name: Cache Cargo build files
        uses: Leafwing-Studios/cargo-cache@v2
        with:
          cargo-target-dir: target
          manifest-path: Cargo.toml

      - name: Install tools
        run: |
          cargo install cargo-llvm-cov
          cargo install cargo-nextest

      - name: Build (release)
        run: cargo build --release --workspace --all-features --all-targets

      - name: Clippy (deny warnings)
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

      - name: Run Tests (Nextest)
        run: RUST_BACKTRACE=1 cargo nextest run --all-features --all-targets --workspace --run-ignored=default
